server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  secret: hireready-secret-key-very-long-and-secure


redis:
  host: localhost
  port: 6379

